export const slfConfig = {
  alphabet: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', // alphabet for dice rolls
  roundEndCountdownSeconds: 4, // seconds to wait before a round ends after stop
  roundRenewTimeout: 2, // seconds to wait after dice roll countdown where nobody can renew the round
  emojis: [
    '🦊',
    '🐻',
    '🦁',
    '🐥',
    '🐨',
    '🐟',
    '🐵',
    '🐷',
    '🐸',
    '🦧',
    '🐈',
    '🦔',
    '🦃',
    '🦥',
    '🦄',
    '🐰',
    '🦆',
    '🐝',
    '🐘',
    '🐞',
    '🎠',
    '😅',
    '👩‍',
    '👧',
    '🤯',
    '😍',
    '😎',
    '😬',
    '😷',
    '🎅',
    '👻',
    '😈',
    '💀',
    '🙋',
    '👯‍♂️',
    '👨‍🌾',
    '👮',
    '👩‍🎓',
    '👩‍🏫',
    '🧑‍💻',
    '👨‍🚀',
    '🧙‍♀️',
    '🤷‍♀️',
    '💩',
    '👑',
    '🧈',
    '🎉',
    '💣',
    '💥',
    '🍆',
    '🥑',
    '🍔',
    '🍑',
    '🍕',
    '🍰',
    '🍷',
  ],
  categories: [
    'Stadt',
    'Land',
    'Fluss',
    'Gewässer',
    'Gebirge/Berg',
    'Hauptstadt',
    'Beruf',
    'Name',
    'Familienname',
    'Mädchenname',
    'Jungenname',
    'Tier',
    'Säugetier',
    'Insekt',
    'Adjektiv',
    'Verb',
    'Farbe',
    'Lebensmittel',
    'Obst',
    'Gemüse',
    'Hauptspeise',
    'Eissorte',
    'Süßigkeit',
    'Pizzabelag',
    'Gewürz',
    'Getränk',
    'Alkoholisches Getränk',
    'Cocktail',
    'Marke',
    'Automarke',
    'Pokémon',
    'Serie',
    'Film',
    'Schauspieler:in',
    'Lied',
    'Musiker:in/Band',
    'Politiker:in',
    'Historische Persönlichkeit',
    'Menschlicher Körper',
    'Krankheit/Symptom',
    'Studiengang',
    'Sportart',
    'Buchtitel',
    'Pflanze',
    'Gefühl',
    'Hobby',
    'Sprache',
    'Fiktive Person oder Charakter',
    'Kleidungsstück',
    'Möbelstück',
    'Elektrisches Gerät',
    'Chemisches Element',
    'Leipzig',
    'Sehenswürdigkeit',
    'Fortbewegungsmittel',
    'kann fliegen',
    'kann schwimmen',
    'Natur',
    'Schimpfwort',
    'Pornotitel',
    'Geschlechtsverkehr Synonym',
    'Trennungsgrund',
    'Todesursache',
    'Schlagzeile',
    'Sprichwort/Bauernregel',
  ],
};
